version: "3.9"

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.email=h.iranshahi67@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/letsencrypt/acme.json

  nginx:
    image: nginx:alpine
    container_name: bots_nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bots.rule=Host(`bots.developerz.ir`)"
      - "traefik.http.routers.bots.entrypoints=websecure"
      - "traefik.http.routers.bots.tls.certresolver=le"
      - "traefik.http.services.bots.loadbalancer.server.port=80"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bots_php
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    restart: always

  mysql:
    image: mariadb:10.11
    container_name: bots_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: developerz_botmanager
      MYSQL_USER: developerz_botmanager
      MYSQL_PASSWORD: uCrqQd5nrHmqnk6m7gdT
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
